new version update
razorpay/razorpay-php pull request #289
Opened 2022-04-26 15:03 UTC by ankitdas13

Doc : https://docs.google.com/document/d/1k9eJ9TmAi-2-ITxgukn2SbQWT5Bflpm77bOXWPHTTlk/edit?usp=sharing

2022-04-27 12:42 UTC, sonyy-m commented
- Update requests library version in razorpay.php
- Rename tests file names to Pascal case (first letter should be uppercase)

2022-04-27 12:42 UTC, sonyy-m commented
- Update requests library version in razorpay.php
- Rename tests file names to Pascal case (first letter should be uppercase)

2022-04-27 12:43 UTC, sonyy-m commented
`Razorpay\Tests\QrCodeTest::testCloseQrCode` testcase failed due to undefined variable $customer. Add test customer_id
https://github.com/razorpay/razorpay-php/blob/b7c94db5044e9c667ec1b974573262a1be730b51/tests/qrCodeTest.php#L84-L88

2022-04-27 12:43 UTC, sonyy-m commented
`Razorpay\Tests\QrCodeTest::testCloseQrCode` testcase failed due to undefined variable $customer. Add test customer_id
https://github.com/razorpay/razorpay-php/blob/b7c94db5044e9c667ec1b974573262a1be730b51/tests/qrCodeTest.php#L84-L88

2022-04-27 12:53 UTC, sonyy-m requested changes
Can we add test payment id in place of `$downtime['items'][0]['id']` to avoid undefined array key 0 error ?
https://github.com/razorpay/razorpay-php/blob/b7c94db5044e9c667ec1b974573262a1be730b51/tests/paymentTest.php#L103-L107

2022-04-28 11:04 UTC, sonyy-m commented on tests/TestCase.php
>          $this->api = new Api( $apiKey, $apiSecret);
Remove Api keys

2022-04-28 11:04 UTC, sonyy-m commented on tests/TestCase.php
>          $this->api = new Api( $apiKey, $apiSecret);
Remove Api keys

2022-04-28 12:11 UTC, ankitdas13 commented on tests/TestCase.php
>          $this->api = new Api( $apiKey, $apiSecret);
removed

2022-04-28 13:17 UTC, sonyy-m approved these changes
LGTM

2022-04-29 11:11 UTC, merged