smartcollect readme correction
razorpay/razorpay-php pull request #311
Opened 2022-06-08 06:24 UTC by ankitdas13

Doc reference : https://razorpay.com/docs/api/smart-collect

2022-06-08 17:45 UTC, sofiya02 requested changes
Fetch Payment Details using ID and Transfer Method - add parameters

2022-06-08 17:45 UTC, sofiya02 commented on documents/virtualaccount.md
> +$options = array("count" => 2);
please remove

2022-06-09 13:05 UTC, ankitdas13 commented on documents/virtualaccount.md
> +$options = array("count" => 2);
removed

2022-06-09 13:05 UTC, ankitdas13 commented on documents/virtualaccount.md
> +$options = array("count" => 2);
removed

2022-06-10 05:36 UTC, sofiya02 requested changes
check response of all api as some of the parameter in response is missing and update them

2022-06-14 13:49 UTC, ankitdas13 commented on documents/virtualaccount.md
> +| paymentId*  | string    | The id of the payment to be updated  |
param updated

2022-06-15 09:18 UTC, sofiya02 approved these changes
LGTM

2022-06-15 12:56 UTC, merged