transfer readme correction
razorpay/razorpay-php pull request #312
Opened 2022-06-08 06:33 UTC by ankitdas13

Doc reference : https://razorpay.com/docs/api/payments/route/

2022-06-08 17:51 UTC, sofiya02 requested changes

2022-06-09 13:07 UTC, ankitdas13 commented on documents/transfer.md
> +| transfers["account"]*   | string     | The id of the account to be fetched   |
done

2022-06-09 13:07 UTC, ankitdas13 commented on documents/transfer.md
> +| transfers["account"]*   | string     | The id of the account to be fetched   |
done

2022-06-10 06:03 UTC, sofiya02 requested changes
Check response of all api

2022-06-13 06:20 UTC, sofiya02 requested changes
check all api with response as mentioned in excel

2022-06-15 09:24 UTC, sofiya02 requested changes
please check the excel and update respective response

2022-06-17 11:37 UTC, sofiya02 approved these changes
LGTM

2022-06-28 10:34 UTC, merged