Qrcode doc correction
razorpay/razorpay-php pull request #313
Opened 2022-06-08 06:40 UTC by ankitdas13

Doc reference :  https://razorpay.com/docs/api/qr-codes/

2022-06-08 17:55 UTC, sofiya02 requested changes

2022-06-08 17:55 UTC, sofiya02 commented on documents/qrcode.md
> +| param["amount"]  | string | Amount to be refunded |
change param[""] to amount and notes

2022-06-08 17:55 UTC, sofiya02 commented on documents/qrcode.md
> +$param = array("amount" => "1000","notes" => array("purpose" => "Test UPI QR code notes"));
$api->payment->fetch($paymentId)->refund(array("amount"=> "100", "speed"=>"normal", "notes"=>array("notes_key_1"=>"Beam me up Scotty.", "notes_key_2"=>"Engage"), "receipt"=>"Receipt No. 31"));

2022-06-09 15:07 UTC, ankitdas13 commented on documents/qrcode.md
> +$param = array("amount" => "1000","notes" => array("purpose" => "Test UPI QR code notes"));
updated

2022-06-10 06:05 UTC, sofiya02 requested changes
unresolved as per comment please recheck

2022-06-13 14:08 UTC, ankitdas13 commented
@sofiya02 use this payment id `pay_JccakgG2EZbHZO` for refund payment

2022-06-15 09:29 UTC, sofiya02 approved these changes
LGTM

2022-06-15 12:57 UTC, merged